FROM python:3-stretch

VOLUME ["/root/serverless"]
WORKDIR /root/serverless

COPY ./cartogram-serverless/requirements.txt /tmp
RUN pip install -r /tmp/requirements.txt

EXPOSE 5050
CMD ["python", "simulate_lambda.py"]
