FROM python:3-stretch

VOLUME ["/root/web"]
WORKDIR /root/web/internal

COPY ./cartogram-web/internal/requirements.txt /tmp
RUN pip install -r /tmp/requirements.txt

EXPOSE 5000
CMD ["sh", "-c", "python -c \"import web; web.db.create_all()\" && python web.py"]
